import { Component, Input, Output } from '@angular/core';
import { SearchComponent } from '../components/search/search.component';
import { HotbarComponent } from '../components/hotbar/hotbar.component';
import { ClassComponent } from '../components/class/class.component';
import { WeeklyScheduleViewComponent } from '../components/weekly-schedule-view/weekly-schedule-view.component';
import { ClassModel } from '../models/class.model';
import { HotbarFComponent } from "../components/hotbar-f/hotbar-f.component";
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-schedule-editor',
  standalone: true,
  imports: [
    SearchComponent,
    HotbarComponent,
    WeeklyScheduleViewComponent,
    HotbarFComponent,
    CommonModule,
    FormsModule
], // Import SearchComponent here
  templateUrl: './schedule-editor.component.html',
  styleUrls: ['./schedule-editor.component.css']
})
export class ScheduleEditorComponent {
  schedule: { [key: string]: any[] } = {};
  days: string[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

  @Input() classes: ClassModel[] = []
  @Input() customEvents: any[] = []

   // Form data for creating a custom event
   customEvent = {
    name: '',
    location: '',
    day: 'Monday',
    startTime: '',
    endTime: '',
  };

  // method to handle loadding classes and custom events into the schedule
  loadSchedule(): void {
    // classModel.classDays will be a string like "MWF" or "TR"
  }

  // method to handle adding class from search results to the weekly schedule view component
  handleAddClass(event: { day: string; classItem: any }): void {
    if (!this.schedule[event.day]) {
      this.schedule[event.day] = [];
    }
    this.schedule[event.day].push(event.classItem);
    console.log(`Class ${event.classItem.className} added to ${event.day}`);
    console.log('Current schedule:', this.schedule);
  }

   // This code was generated by GitHub Copilot and modified
   // Method to handle adding a custom event
   addCustomEvent(): void {
    const event = { ...this.customEvent, isInSchedule: true };
    if (!this.schedule[event.day]) {
      this.schedule[event.day] = [];
    }
    this.schedule[event.day].push(event);
    console.log(`Custom event ${event.name} added to ${event.day}`);
    console.log('Current schedule:', this.schedule);

    // Reset the form
    this.customEvent = {
      name: '',
      location: '',
      day: 'Monday',
      startTime: '',
      endTime: '',
    };
  }
}